Repository atlp-rwanda/ecommerce-app-champions-bn, pull requests merged in 2023-05, with the labels that each got.

#54 #23 Fix Vendor Two factor authentication
  .env.example
  src/api-docs/user.docs.js
  src/controllers/resetPasswordController.js
  src/controllers/roleController.js
  src/controllers/userController.js
  src/database/migrations/20230326192254-create-user.js
  src/jobs/checkExpiredPassword.js
  src/routes/Oauthroute.js
  src/routes/buyer.route.js
  src/routes/user.route.js
  src/services/profile.service.js
  src/utils/verifyPassword.js
  test/buyer.test.js
  test/twoFactorAuth.test.js
  test/user.test.js
  test/vendor.test.js
Labels: ready for review

#55 fix : fix update and get profile
  .env.example
  src/controllers/vendorController.js
  src/routes/vendor.route.js
Labels: fix

#56 # fix: clear and delete a product from the buyer's cart
  src/api-docs/cart.docs.js
  src/controllers/cartController.js
  src/locales/fr/translation.json
  src/locales/kin/translation.json
  src/routes/cart.route.js
  test/buyer.test.js
Labels: ready for review, fix

#58 fix:create buyer's checkout and payment
  src/api-docs/product.docs.js
  src/api-docs/user.logout.docs.js
  src/controllers/Oauthcontroller.js
  src/controllers/paymentController.js
  src/middlewares/checklogin.js
  src/routes/Oauthroute.js
  src/routes/product.route.js
  src/utils/helpers/generateToken.js
  test/buyer.test.js
  test/product.test.js
Labels: ready for review

#59 Fix product review
  src/api-docs/product.docs.js
  src/api-docs/review.docs.js
  src/controllers/cartController.js
  src/controllers/productController.js
  src/controllers/reviewController.js
  src/controllers/vendorController.js
  src/middlewares/authenticate.js
  src/routes/permission.route.js
  src/routes/review.route.js
  src/routes/vendor.route.js
  src/utils/handleCookies.js
  src/validations/validateReview.js
  test/buyer.test.js
  test/review.test.js
Labels: ready for review

#60 fix Notifications
  src/api-docs/notification.docs.js
  src/controllers/notificationController.js
  src/controllers/paymentController.js
  src/controllers/productController.js
  src/database/config/config.js
  src/database/models/notification.js
  src/events/notifications.js
  src/index.js
  src/jobs/checkExpiredPassword.js
  src/middlewares/authenticate.js
  src/routes/notification.route.js
Labels: ready for review
